server:
  port: 18011

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC

api:
  basic:
    authentication:
      username: admin
      password: 'q1w2e3'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local
---

spring:
  config:
    activate:
      on-profile: local-db

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    generate-ddl: true
    hibernate.ddl-auto: update  # create, create-drop, update, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

postgresql:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:15432/keymedi
    username: flower
    password: ffdb

---
